name: Pytests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install autopep8 pylint radon pytest

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src:$(pwd)/tests" >> $GITHUB_ENV

      - name: Run autopep8
        run: |
          autopep8 --in-place --aggressive --aggressive src/hw2/hw2_debugging.py
      - name: Run linting
        run: |
          pylint src/hw2/hw2_debugging.py --exit-zero

      - name: Run Radon Cyclomatic Complexity
        run: |
          radon cc -nc src/hw2/hw2_debugging.py

      - name: Run tests
        run: pytest tests/hw2/

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
